### ISSUE TITLE
Support ignore and keep empty system environments

### ISSUE THREAD

**Issue by MadeInChina** [a8m/envsubst#25]
e.g 
I have prometheus config below which want only replace CONSUL_URL from system environment. but it will replace $1 left blank there  which make __metrics_path__ not correct. 
```
  - job_name: 'consul'
    metrics_path: '/actuator/prometheus'
    consul_sd_configs:
      - server: '${CONSUL_URL:-127.0.0.1:8500}'
        services: [] #match all service
    relabel_configs:
      - source_labels: [__meta_consul_service]
        target_label: job
      - source_labels: [__meta_consul_service_metadata_management_context_path]
        regex: "(.+)"
        target_label: __metrics_path__
        replacement: '$1/prometheus'
```
